version: 2
jobs:
  build:
    working_directory: ~/jest
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run:
        name: "Run Jest and Collect Coverage Reports"
        command: jest --collectCoverage=true
      - store_artifacts:
          path: coverage