version: 2
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    parallelism: 3
    docker:
      # I want to make sure I know exactly what version I'm using
      - image: circleci/node:10.16.3

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm ci

      - codecov/upload:
          flags: backend,unittest

      - run:
          name: Run Jest tests using test splitting
          command: |
            TESTFILES=$(circleci tests glob "test/**/*.test.js" | circleci tests split --split-by=timings)
            npm test $TESTFILES

      - store_test_results:
          path: test_results

      - store_artifacts:
          path: test_results
          destination: test_results

      - codecov/upload:
          file: coverage/*.json
          flags: frontend